In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.4'

In [4]:
arr=[1,2,3,4,5,6]

In [5]:
narr=np.array(arr)
narr

array([1, 2, 3, 4, 5, 6])

Random Module with rand Function

In [7]:
np.random.rand(10,2)

array([[0.73007982, 0.37991358],
       [0.9663532 , 0.51087997],
       [0.93810879, 0.08762534],
       [0.96352891, 0.34588454],
       [0.57803346, 0.4177587 ],
       [0.39656171, 0.34390283],
       [0.75355408, 0.47086986],
       [0.65650633, 0.54766908],
       [0.31037184, 0.61358631],
       [0.25429276, 0.71290656]])

In [9]:
np.random.rand(10,5)

array([[0.42876632, 0.35670861, 0.84102923, 0.06315272, 0.91792052],
       [0.6164992 , 0.76135901, 0.6127946 , 0.30769341, 0.8875354 ],
       [0.85883793, 0.19852866, 0.20455021, 0.76421965, 0.73217567],
       [0.27755657, 0.08729252, 0.06161495, 0.03720634, 0.45635688],
       [0.48900856, 0.92207947, 0.02799836, 0.82572465, 0.98816432],
       [0.36037646, 0.8775143 , 0.71546953, 0.23091708, 0.00156084],
       [0.59120066, 0.59306339, 0.55893626, 0.81819505, 0.2612947 ],
       [0.45305324, 0.92575364, 0.24625099, 0.87931448, 0.88796212],
       [0.91508034, 0.28112797, 0.70753057, 0.22515752, 0.9768454 ],
       [0.88798831, 0.52422766, 0.83408232, 0.73807431, 0.60973103]])

Negative matrix

In [11]:
np.random.randn(3,3,3)

array([[[ 0.118387  ,  0.0641161 ,  1.37987926],
        [-0.35287589,  0.57821431,  1.02179513],
        [-1.20600315,  0.51887742, -0.85936522]],

       [[-0.16077831,  1.22738758, -1.00126629],
        [ 1.45762399, -3.17498707,  0.57764576],
        [-2.03430091, -0.55991704,  0.35077183]],

       [[-1.08332751, -0.96857357,  0.45321579],
        [ 1.01114346,  0.24843146,  0.4270814 ],
        [-0.76760394,  0.11434035,  0.35765164]]])

intiger number print with range & Reshape

In [18]:
lol=np.random.randint(10,21,size=[5,2,3])

In [19]:
lol.shape

(5, 2, 3)

In [22]:
lol.reshape(3,10)

array([[14, 11, 11, 19, 19, 11, 17, 17, 14, 18],
       [19, 20, 15, 18, 17, 10, 14, 10, 11, 17],
       [20, 10, 11, 19, 19, 12, 14, 12, 10, 16]], dtype=int32)

In [23]:
lol

array([[[14, 11, 11],
        [19, 19, 11]],

       [[17, 17, 14],
        [18, 19, 20]],

       [[15, 18, 17],
        [10, 14, 10]],

       [[11, 17, 20],
        [10, 11, 19]],

       [[19, 12, 14],
        [12, 10, 16]]], dtype=int32)

In [ ]:
lol.min()
lol.max()


np.int32(20)